// The ones listed at the beginning(top) are prioritised to be featured if 3 works are not selected
export const worksData = [
	{
		name: "Affirm Care",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://affirmcare.com.au/",
		repo: "https://github.com/tomokawaguchi/",
		featuredImage: "affirm-featured.png",
		snapshots: ["affirm-snapshot.png"],
		featured: false,
		id: "1",
	},
	{
		name: "St.Stephens School",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://www.ststephens.wa.edu.au/",
		repo: "https://github.com/tomokawaguchi/",
		featuredImage: "ststephens-featured.png",
		snapshots: ["ststephens-snapshot.png", "ststephens-snapshot.png"],
		featured: true,
		id: "2",
	},
	{
		name: "ECU Strategic Plan",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://strategicplan.ecu.edu.au/",
		repo: "https://github.com/tomokawaguchi/",
		featuredImage: "ecu-featured.png",
		snapshots: ["ecu-snapshot.png"],
		featured: false,
		id: "3",
	},
	{
		name: "Verge Valet",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://www.vergevalet.com.au/",
		repo: "ttps://github.com/tomokawaguchi/",
		featuredImage: "vv-featured.png",
		snapshots: ["vv-snapshot.png", "vv-snapshot.png", "vv-snapshot.png"],
		featured: false,
		id: "4",
	},
	{
		name: "VHM Limited",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://www.vhmltd.com.au/",
		repo: "https://github.com/tomokawaguchi",
		featuredImage: "vhm-featured.png",
		snapshots: ["vhm-snapshot.png", "vhm-snapshot.png", "vhm-snapshot.png"],
		featured: false,
		id: "5",
	},
	{
		name: "Living Pround",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://www.livingproud.org.au/",
		repo: "https://github.com/tomokawaguchi/",
		featuredImage: "lv-featured.png",
		snapshots: ["lv-snapshot.png"],
		featured: false,
		id: "6",
	},
	{
		name: "Julius Captures",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://juliuscaptures.com.au/",
		repo: "https://github.com/tomokawaguchi/",
		featuredImage: "jc-featured.png",
		snapshots: ["jc-snapshot.png"],
		featured: false,
		id: "7",
	},
	{
		name: "Flexi Tennis Leagues",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://flexitennisleagues.com.au/",
		repo: "",
		featuredImage: "flexi-featured.png",
		snapshots: ["flexi-snapshot.png"],
		featured: true,
		id: "8",
	},
	{
		name: "Robo Friends",
		desc: "Personal project in Rect. The robots data is dynamically obtained and rendered through API. The filter functionality allows you to filter by your typed word and display the filtered list of robots live. This app was created to understand the React foundamentals and the concept of components.",
		liveLink: "https://tomokawaguchi.github.io/robofriends/",
		repo: "https://github.com/tomokawaguchi/robofriends",
		featuredImage: "rb-featured.png",
		snapshots: [],
		featured: true,
		id: "9",
	},
];
