// The ones listed at the beginning(top) are prioritised to be featured if 3 works are not selected
export const worksData = [
	{
		name: "Project Name 1",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://affirmcare.com.au/1",
		repo: "https://github.com/tomokawaguchi/portfolio-project",
		featuredImage: "affirm-featured.png",
		snapshots: ["snapshot.png", "snapshot.png", "snapshot.png"],
		featured: false,
		id: "1",
	},
	{
		name: "Project Name 2",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://affirmcare.com.au/2",
		repo: "https://github.com/tomokawaguchi/portfolio-project",
		featuredImage: "affirm-featured.png",
		snapshots: ["snapshot.png", "snapshot.png", "snapshot.png"],
		featured: true,
		id: "2",
	},
	{
		name: "Project Name 3",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://affirmcare.com.au/3",
		repo: "https://github.com/tomokawaguchi/portfolio-project",
		featuredImage: "affirm-featured.png",
		snapshots: ["snapshot.png", "snapshot.png", "snapshot.png"],
		featured: true,
		id: "3",
	},
	{
		name: "Project Name 4",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://affirmcare.com.au/4",
		repo: "ttps://github.com/tomokawaguchi/portfolio-project",
		featuredImage: "affirm-featured.png",
		snapshots: ["snapshot.png", "snapshot.png", "snapshot.png"],
		featured: false,
		id: "4",
	},
	{
		name: "Project Name 5",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://affirmcare.com.au/5",
		repo: "https://github.com/tomokawaguchi/portfolio-project",
		featuredImage: "affirm-featured.png",
		snapshots: ["snapshot.png", "snapshot.png", "snapshot.png"],
		featured: true,
		id: "5",
	},
	{
		name: "Project Name 6",
		desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
		liveLink: "https://affirmcare.com.au/6",
		repo: "https://github.com/tomokawaguchi/portfolio-project",
		featuredImage: "affirm-featured.png",
		snapshots: ["snapshot.png", "snapshot.png", "snapshot.png"],
		featured: false,
		id: "6",
	},
];
